### ISSUE TITLE
请问一直找不到beadbun这个类是哪里的原因呢？

### ISSUE THREAD

**Issue by voocel** [kiddyuchina/Beanbun#1]
![Uploading 6666.png…]()

[root@localhost www]# ls
composer.json  composer.lock  vendor
[root@localhost www]# vim start.php
[root@localhost www]# php start.php
PHP Fatal error:  Uncaught Error: Class 'Beanbun\Beanbun' not found in /www/start.php:3
Stack trace:
#0 {main}
  thrown in /www/start.php on line 3
[root@localhost www]# 

这是刚刚用composer安装好，然后复制了start.php执行的结果

**Comment by kiddyuchina** [comment]
你的图没有看到。
如果是完全复制 REMDME.md 上的代码话，需要在最前面引入 composer 的自动加载文件
`require_once __DIR__ . '/vendor/autoload.php';`
这句忘了加上了，不好意思

**Comment by voocel** [comment]
@kiddyuchina ok 谢谢

**Comment by onePieceAce** [comment]
![image](https://user-images.githubusercontent.com/22976939/28412009-64b15f82-6d75-11e7-947f-1ceedbfb7d40.png)
官方文档看不明白，请问这个use Beanbun\Beanbun;什么意思？

**Comment by kiddyuchina** [comment]
@onePieceAce 这个是 PHP 的命名空间，请搜索一下命名空间与 composer 的相关知识
