### ISSUE TITLE
守护模式下报错cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by qintian0125** [kiddyuchina/Beanbun#11]
我爬取糗百的网址数据时，在守护模式下，日志中一直有cURL error 3: <url> malformed这个错误，请问是哪里有问题啊？

**Comment by jackwangshukai** [comment]
> 我爬取糗百的网址数据时，在守护模式下，日志中一直有cURL error 3: malformed这个错误，请问是哪里有问题啊？
我也遇到这个问题了如何解决

**Comment by kiddyuchina** [comment]
请升级到 dev-master 版本
