### ISSUE TITLE
文档打不开

### ISSUE THREAD

**Issue by CmderQ** [kiddyuchina/Beanbun#22]
http://www.beanbun.org/#/
这个网址的文档，不知道为什么，打不开！~

**Comment by taozywu** [comment]
@CmderQ 的确打不开，不过如果你想看doc。你可以看这里

https://github.com/kiddyuchina/Beanbun/tree/master/docs/chs

**Comment by CmderQ** [comment]
@taozywu 谢谢！

**Comment by marsberrys** [comment]
官网加载不出来呢

**Comment by CmderQ** [comment]
@marsberrys 是的，也不知道是为啥！

**Comment by kiddyuchina** [comment]
@CmderQ @taozywu @marsberrys 文档解析的 js 出了问题，现在文档可以访问了。
