### ISSUE TITLE
除了手工执行 php start.php stop 之外，怎样在代码里正确退出？

### ISSUE THREAD

**Issue by xtremforce** [kiddyuchina/Beanbun#25]
守护模式下，除了手工执行 php start.php stop 来停止之外，在代码里可以怎样可以正确地停止？
比如写个 timer 检查到 redis 队列为空之后，自动退出。

**Comment by kiddyuchina** [comment]
在dev-master版本里有shutdown方法可以退出爬虫。
`$beanbun->shutdown();`
