### ISSUE TITLE
我如果去请求post的接口的话参数如何传递没看到文档里有写啊

### ISSUE THREAD

**Issue by jackwangshukai** [kiddyuchina/Beanbun#33]

**Comment by kiddyuchina** [comment]
在 $options 中可以设置 method。
```
$beanbun->queue()->add($url, [
    'method' => 'POST'
]);
```
http://www.beanbun.org/#/?id=queue-%E9%98%9F%E5%88%97

**Comment by jackwangshukai** [comment]
> 在 $options 中可以设置 method。
> 
> ```
> $beanbun->queue()->add($url, [
>     'method' => 'POST'
> ]);
> ```
> http://www.beanbun.org/#/?id=queue-%E9%98%9F%E5%88%97



> 在 $options 中可以设置 method。
> 
> ```
> $beanbun->queue()->add($url, [
>     'method' => 'POST'
> ]);
> ```
> http://www.beanbun.org/#/?id=queue-%E9%98%9F%E5%88%97

这个是在队里里请求的url设置。比如我启动的url。seed 里怎么设置请求方法为post

**Comment by kiddyuchina** [comment]
```
$beanbun->seed = [
    'http://www.950d.com/',
    [
        'http://www.950d.com/list-2.html',
        [
            'method' => 'POST',
        ]
    ]
];
```

**Comment by jackwangshukai** [comment]
> ```
> $beanbun->seed = [
>     'http://www.950d.com/',
>     [
>         'http://www.950d.com/list-2.html',
>         [
>             'method' => 'POST',
>         ]
>     ]
> ];
> ```

这种是可以的。但是我发现一个别的问题。就是当队列里没有url了之后，还是会去请求。这时候就会报错。



2018-10-19 15:59:58 test : cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
2018-10-19 15:59:58 test : cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
打出来看请求的url 是null

**Comment by kiddyuchina** [comment]
这个问题先更新 dev-master 版本吧

**Comment by jackwangshukai** [comment]
> 这个问题先更新 dev-master 版本吧

这个如何更新？

**Comment by googles8** [comment]
设定post后，data数据在那里设定啊？能不能举一个post的例子呢。 'method' => 'POST', 要传递的post数据，跟在后面好像不行呢，麻烦解答下，谢谢

**Comment by kiddyuchina** [comment]
@googles8 
下面放了两个例子，更多的参数可以参考 Guzzle 的[文档](http://docs.guzzlephp.org/en/stable/request-options.html)
```
$beanbun->queue()->add($url, [
    'method' => 'POST',
    // application/x-www-form-urlencoded
    'form_params' => [
        'foo' => 'bar',
        'baz' => 'hi', 
    ],
    // application/json
    'json' => [
         'foo' => 'bar',
        'baz' => 'hi', 
    ],
]);
```

**Comment by googles8** [comment]
谢谢回复。Guzzle 的文档看了，只是没找到你这个类中与'form_params'对应的参数放哪里。

我按你的$url='http://httpbin.org/post';
$beanbun->queue()->add($url, [
    'method' => 'POST',
    // application/x-www-form-urlencoded
    'form_params' => [
        'foo' => 'bar',
        'baz' => 'hi', 
    ],
    // application/json
    'json' => [
         'foo' => 'bar',
        'baz' => 'hi', 
    ],
]);
其余默认。结果报错。因为queue()好像是守护进程下才有。
在普通模式下，如何传参呢？
$beanbun->seed = [
    'http://www.950d.com/',
    [
        'http://httpbin.org/post',
        [
            'method' => 'POST',
			'form_params' => [
					'foo' => 'bar',
					'baz' => 'hi', 
				],
        ]
    ]
];

我依照例子这样写网址，好像也不行。 麻烦给下指点。谢谢
