### ISSUE TITLE
max 属性的作用是什么呢？

### ISSUE THREAD

**Issue by cheihcheung** [kiddyuchina/Beanbun#38]
已经给设定$beanbun->max = 3; 
但是爬虫会不停的爬，如果是长期爬取某一个网站，爬过的地址是不是存数据库比较准吧

**Comment by kiddyuchina** [comment]
max 是定义当前爬虫最大抓取网页数量，如抓取达到此数则停止抓取，为0时不限制抓取数量，默认为0。int 类型，可选设置。
有问题的话用 dev-master 版本试试？
看网址有没有爬取过，数据库当然是比布隆过滤器可靠。

**Comment by cheihcheung** [comment]
好的。谢谢！
