### ISSUE TITLE
可以解析网页吗？

### ISSUE THREAD

**Issue by Kooooooma** [kiddyuchina/Beanbun#4]
爬虫框架我理解就是下载网页，对于下载下来的网页不不能进行分析，比如说提前网页标题，提取关键字，提取网页主内容摘要，缩略图这些是基本的，更高级别的还有很多了。

请问下作者你这个框架除了支持各种方式爬取之外，对爬下来的网页做进一步处理支持什么呢？或者有提供一种插件的形式可以让使用者自己来处理。

**Comment by kiddyuchina** [comment]
对页面的解析和整体爬虫框架耦合性比较低，而且在现在 composer 上有大量优秀成熟的页面处理的轮子的情况下，感觉让大家使用自己喜欢的方式去处理更好，所以框架没有内置这个功能。在这里推荐几个轮子:
1.didom
2.phpquery
3.querylist
前两个都是很出名的页面解析的包，都是是用类似于jquery的语法，最后一个是国人在phpquery基础上开发的，可以很方便的获取页面中的列表内容，返回数组。这三个都是可以 composer 引入之后直接使用的。
后边会根据大家的反馈制作个插件来处理页面，如果大家能制作个插件提供出来就更好了😁

**Comment by kiddyuchina** [comment]
写了个数据抽取的插件 [beanbun-parser](https://github.com/kiddyuchina/beanbun-parser) 可以看一下
