### ISSUE TITLE
JS动态渲染后的页面能处理吗？

### ISSUE THREAD

**Issue by jiangnianzhong** [kiddyuchina/Beanbun#6]
没有用过，有这么一个疑问，如果不能抓取JS渲染后的数据，那能不能配合phantomjs一起工作？

**Comment by kiddyuchina** [comment]
可以。
可以设置 downloadPage 回调函数对下载过程进行修改。写了个简单的[示例](https://github.com/kiddyuchina/Beanbun/blob/master/examples/phantomjs.php)，是使用 phantomjs 对 js 渲染后的页面进行截图。例子使用了 [php-phantomjs](https://github.com/jonnnnyw/php-phantomjs) 包。

相关文档位置：
下载器设置：http://www.beanbun.org/#/?id=setdownloader
下载过程设置：http://www.beanbun.org/#/?id=downloadpage
