### ISSUE TITLE
PHP Warning:  array_flip()

### ISSUE THREAD

**Issue by zhaoqy** [kiddyuchina/Beanbun#9]
PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /vendor/kiddyu/beanbun/src/Lib/Helper.php on line 44

有时间up一下，^_^

**Comment by ThroughLee** [comment]
@zhaoqy 我也碰到这个问题了， 是因为 Helper 类里的 getUrlByHtml 没有对 url 做校验，导致 array_flip 的时候 value 有可能出现非 string  integer， 所以出现这个 warning.
@kiddyuchina

**Comment by kiddyuchina** [comment]
试一下 `composer require kiddyu/beanbun dev-master` 是否可以解决

**Comment by ThroughLee** [comment]
我试了一下 dev-master， 没有这个问题。
👍
